"""A file that exists in the working tree and not in the repository is invisible to every check.

Rounds seventy-nine to eighty-five built four artefacts so that measurements could be re-checked
without the 99 MB Anthology corpus: the 70 machine-written abstracts that are the AI arm of the
AUROC inversion, the register corpus, the survey counts, and the tell base rates. The ledger
describes all four as committed. **None of them was.** `.gitignore` carried `data/` for downloaded
corpora, that pattern matches `eval/data/` at any depth, and `git add -A` silently skipped them for
eight rounds.

Nothing caught it because every check in this repository — the audit, the doc guards, the whole test
suite — runs in a working tree where the files are present. The failure mode is the worst kind: the
single most consequential measurement here was not reproducible from the repository, and the
document saying it was reproducible was itself the evidence that it was.

This test asks git, not the filesystem. It is deliberately not a check on `.gitignore`'s text: the
rule that broke this was correct for its purpose and wrong only in reach, so what needs asserting is
the outcome — the files are in the repository — rather than the spelling of any one pattern.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent

# Each of these is read at import or at run time by code that has no fallback if it is missing.
REQUIRED = [
    "eval/data/generated_abstracts.py",
    "eval/data/generated_registers.py",
    "eval/data/survey_counts.json",
    "eval/data/tell_base_rates.json",
    "eval/data/window_sweep.json",
]


def _tracked() -> set[str]:
    out = subprocess.run(
        ["git", "ls-files"], cwd=REPO, capture_output=True, text=True, check=True,
    ).stdout
    return set(out.splitlines())


needs_git = pytest.mark.skipif(
    not (REPO / ".git").exists(), reason="not a git checkout (sdist or installed copy)",
)


@needs_git
@pytest.mark.parametrize("path", REQUIRED)
def test_the_artefact_is_in_the_repository_not_just_on_this_disk(path: str):
    assert (REPO / path).exists(), f"{path} is missing from the working tree"
    assert path in _tracked(), (
        f"{path} exists here and is not committed. Every test that reads it passes on this "
        f"machine and fails on a fresh clone, and any document calling it reproducible is wrong. "
        f"Add it with `git add -f {path}` and fix the .gitignore rule that swept it up."
    )


@needs_git
def test_nothing_under_eval_data_is_quietly_ignored():
    """The directory is evidence, not cache. A new artefact must not repeat the same disappearance."""
    present = {
        str(p.relative_to(REPO))
        for p in (REPO / "eval" / "data").rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }
    missing = sorted(present - _tracked())
    assert not missing, (
        f"untracked file(s) under eval/data: {missing}. This directory holds hand-authored evidence "
        f"that cannot be regenerated by downloading anything, so an untracked file here is lost "
        f"work that still reads as present."
    )


@needs_git
def test_the_ai_arm_of_the_inversion_finding_survives_a_fresh_clone():
    """The headline negative result must be re-derivable from the repository alone.

    `eval/detection_power.py` needs the Anthology cache for the human arm — that is a documented
    download. The machine arm is not downloadable from anywhere: a language model wrote it, and if
    it is not in the repository it does not exist.
    """
    tracked = _tracked()
    assert "eval/data/generated_abstracts.py" in tracked
    from eval.data import generated_abstracts

    assert len(generated_abstracts.ABSTRACTS) >= 70, (
        "the published figures rest on 70 machine-written abstracts"
    )
